config:
  service:
      name: jackson-api
      port: 8080
      labelName: jackson
  # fullnameOverride: spring-boot-api
  appName: spring-boot-api
  enableVirtualService: true
  enableDestinationRule: true
subcomponents:
  canary:
    config:
      appName: spring-boot-api
      fullnameOverride: api-deploy-canary
  stable:
    config:
      appName: spring-boot-api
      fullnameOverride: api-deploy-stable