  config:
  subcomponents:
    infra:
        subcomponents:
            fabrikate-cloud-native:
                subcomponents:
                    prometheus-grafana:
                        subcomponents:
                            grafana:
                                config:
                                    adminPassword: "[test]"