apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-app-ui.fullname" . }}
  labels:
    app: {{ .Values.abstractName }}
    helm.sh/chart: {{ include "spring-boot-app-ui.chart" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "spring-boot-app-ui.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
