apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labelName }}
spec:
  host: {{ .Values.service.name }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary